source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


target 'ResearchKitExtension_Tests', :exclusive => true do
  pod "ResearchKitExtension", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
